import Banner from './Banner'
import Girl from './Girl'
import LoginForm from './LoginForm'
import NearestCenter from './pages/find-center/NearestCenter'
import InjectorInfo from './pages/register-vaccine/InjectorInfo'
import Information from './pages/my-account/Information'
import VcInjected from './pages/my-account/VcInjected'
import {Title, Item, exampleSelfData } from './pages/register-vaccine/InjectorInfo'
import RelatedInfo, { exampleAnotherData } from './pages/register-vaccine/RelatedInfo'
import Packages from './Packages'
import Vaccines from './Vaccines'
import VaccineItem from './VaccineItem'
import VcRecommend from './VcRecommend'
import { RegisVcContext, RegisVcProvider } from './context/RegisVcContext'

export { Banner, Girl, LoginForm, NearestCenter, InjectorInfo, RelatedInfo, Title, Item, Packages, Vaccines, VaccineItem, RegisVcContext, RegisVcProvider, exampleSelfData, exampleAnotherData, Information, VcInjected, VcRecommend }